Update docker-scan.yaml

diff --git a/.github/workflows/docker-scan.yaml b/.github/workflows/docker-scan.yaml
--- a/.github/workflows/docker-scan.yaml
+++ b/.github/workflows/docker-scan.yaml
@@ -16,7 +16,7 @@ jobs:
         id: scan
         with:
           image: "localbuild/testimage:latest"
-          fail-build: false #change to true to fail if security issues found
+          fail-build: true #change to true to fail if security issues found
           severity-cutoff: critical
           output-format: json
           by-cve: true
@@ -28,11 +28,14 @@ jobs:
           compression-level: 1
       - name: setup python
         uses: actions/setup-python@v5
+        if: ${{ success() || failure() }}
         with:
           python-version: 3.11.8
       - name: pip install
+        if: ${{ success() || failure() }}
         run:  pip install argparse pandas
       - name: Print Results
+        if: ${{ success() || failure() }}
         env:
           path: ${{ steps.scan.outputs.json }}
         run: |
